###
POST /signup HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "userId": "testuser",
  "userPassword": "password123",
  "userEmail": "test@example.com",
  "userName": "테스트유저"
}

###