###
POST /signup HTTP/1.1
Host: localhost:7070
Content-Type: application/json

{
  "userId": "testuser",
  "userPassword": "password123",
  "userEmail": "test@example.com",
  "userName": "테스트유저"
}

###
GET /login?userId=testuser&userPassword=password123 HTTP/1.1
Host: localhost:7070