spring:
  application:
    name: ink3-eureka
  config:
    import: optional:configserver:https://ink3.shop/config/
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
  cloud:
    bus:
      enabled: true