server:
  shutdown: graceful
  port : 10252

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

  web:
    resources:
      add-mappings: true

  mvc:
    pathmatch:
      matching-stragtegy: ant_path_matcher

  security:
    user:
      name: admin
      password: 1234

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: >
        http://admin:1234@localhost:10252
