server:
  shutdown: graceful
  port : 10252

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

  security:
    user:
      name: admin
      password: 1234

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: >
        http://admin:1234@localhost:10252/eureka
